name: CD

on:
  push:
    tags: ["*"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
      - run: uv sync --frozen
      - run: uv build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release:
    runs-on: ubuntu-24.04
    needs: build-release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: asimov-platform/release-action@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          changelog-path: CHANGES.md
          compute-checksum: false

  publish:
    runs-on: ubuntu-24.04
    needs: release
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
          continue-on-error: true
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"
          enable-cache: true
      - env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish --token $UV_PUBLISH_TOKEN dist/*
        working-directory: .

